### ISSUE TITLE
OPCN3

### ISSUE THREAD

**Issue by amguardia** [MarcelloYung/opcn2-Arduino#4]
The update by the aphasense firm of its OPC-N2 sensor to N3 causes that the library can no longer be used in new projects have any update available for the new sensor ... the user marlon360 (https://github.com/marlon360/opcn3-arduino) recently published a library in this regard but lacks documentation for use or examples

**Comment by nmarcelo** [comment]
I saw that an example was added by marlon360, therefore i am closing this issue.
